name: unit-tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: [ edx-platform-runner ]
    strategy:
      matrix:
        python-version: ['3.8']
        django-version: ["3.2"]
        shard_name: [
            "lms-1",
            "lms-2",
            "lms-3",
            "lms-4",
            "lms-5",
            "lms-6",
            "openedx-1",
            "openedx-2",
            "openedx-3",
            "openedx-4",
            "cms-1",
            "cms-2",
            "common-1",
            "common-2",
            "common-3",
        ]


    name: python-${{ matrix.python-version }},django-${{ matrix.django-version }},${{ matrix.shard_name }}
    steps:
      - name: sync directory owner
        run: sudo chown runner:runner -R .*
      - uses: actions/checkout@v2
      - name: start mongodb service
        run: |
          echo "Check for lock files and similar"
          ls -Al /var/lib/mongodb/
          echo

          echo "get status"
          sudo /etc/init.d/mongodb status || { echo "(ignoring status failure, moving on)" }
          echo

          echo "try starting"
          sudo /etc/init.d/mongodb start || {
            sudo ls -al /var/log/
            sudo grep -lIir mongo /var/log/
            exit 1
          }
          echo

          echo "Looking again at lock files"
          ls -Al /var/lib/mongodb/
          echo
