name: unit-tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: [ edx-platform-runner ]
    strategy:
      matrix:
        python-version: ['3.8']
        django-version: ["3.2"]
        shard_name: [
            "lms-1",
            "lms-2",
            "lms-3",
            "lms-4",
            "lms-5",
            "lms-6",
            "openedx-1",
            "openedx-2",
            "openedx-3",
            "openedx-4",
            "cms-1",
            "cms-2",
            "common-1",
            "common-2",
            "common-3",
        ]


    name: python-${{ matrix.python-version }},django-${{ matrix.django-version }},${{ matrix.shard_name }}
    steps:
      - name: sync directory owner
        run: sudo chown runner:runner -R .*
      - uses: actions/checkout@v2
      - name: start mongodb service
        run: |
          maxtries=5
          attempt=1
          while true; do
            if sudo /etc/init.d/mongodb start; then
              break
            elif [[ "$attempt" -ge "$maxtries" ]]; then
              echo "Failed to start Mongo in $attempt tries, giving up."
              exit 1
            else
              echo "Failed to start Mongo (attempt $attempt), sleeping and trying again"
              (( attempt++ ))
              sleep 5
            fi
          done
